name: CI/CD Pipeline - Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.8'

    - name: Install dependencies 
      run: pip install -r requirements.txt 
      
    # - name: Run tests with coverage
    #   run: pytest --cov=quiz_app quiz_app/tests/test_quiz.py --cov-report=xml
    - name: Run tests with coverage
      run: pytest

    - name: Upload coverage to Codecov 
      uses: codecov/codecov-action@v4
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}